repos:
  - repo: local
    hooks:
      - id: quarto-render
        name: Build site
        entry: "bash precommit.sh"
        language: system
        always_run: true
        pass_filenames: false
