project:
  type: website
  output-dir: .

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    right:
      - text: Home
        href: index.qmd
      
format:
  html:
    theme: [cosmo, styles.scss]

